"""empty message

Revision ID: 84b7eba1b27a
Revises: 393be3134177
Create Date: 2019-07-18 23:03:37.305432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b7eba1b27a'
down_revision = '393be3134177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('done', sa.String(length=5), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('done', table_name='todos')
    op.drop_index('label', table_name='todos')
    op.drop_table('todos')
    op.drop_index('email', table_name='person')
    op.drop_index('username', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'person', ['username'], unique=True)
    op.create_index('email', 'person', ['email'], unique=True)
    op.create_table('todos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('done', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['person.id'], name='todos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('label', 'todos', ['label'], unique=True)
    op.create_index('done', 'todos', ['done'], unique=True)
    op.drop_table('todo')
    # ### end Alembic commands ###
